### ISSUE TITLE
Add to my project.

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Figma-Locofi-Netlify#1]
Hey Geeks Contribute to my project.

**Comment by SunilKumar-K** [comment]
@Ctoic  can you explain what is going in this project

**Comment by Ctoic** [comment]
Yeah sure, I was developing a UI using Figma and came to know about this
amazing AI tool known as locofy which was converting your Figma file to
code directly so you can deploy your webpages Instantly. In addition
Netlify is a platform where you can deploy your websites for free

**Comment by SunilKumar-K** [comment]
shall we meet once @Ctoic  you can explain more to me about this project

**Comment by Ctoic** [comment]
Yes why not we will.
